kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
  configs:
    group-id: ${CONSUMER_GROUP_ID:customer-ms-group}
    auto-offset-reset: ${AUTO_OFFSET_RESET:earliest}
  topics:
    update-balance: ${UPDATE_BALANCE_TOPIC:sbank.customer-ms.update-balance}